name: Generar Noticias Diarias

on:
  schedule:
    - cron: '0 12 * * *'  # Ejecutar diario a las 12 PM UTC
  workflow_dispatch:

jobs:
  generate-news:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Instalar dependencias
        run: |
          pip install feedparser transformers torch
          
      - run: python scripts/generate_news.py
      
      - name: Subir cambios
        run: |
          git config --global user.name "Auto News Bot"
          git config --global user.email "bot@news.com"
          git add src/posts/
          git commit -m "Auto: Actualización de noticias del día" || echo "Sin cambios"
          git push